server:
  host: localhost
  port: 9999
  protocol: tcp
bigcache:
  shards: 1024
  lifeWindow: 10
  maxEntriesInWindow: 600000
  maxEntrySize: 500
  verbose: true
  hardMaxCacheSize: 0
amqp:
  host: 192.168.99.100
  port: 5672 
  exchange: logexchange
  user: 
  password: 